### ISSUE TITLE
Bad groupId, or an old version on mvnrepository?

### ISSUE THREAD

**Issue by filipncs** [vy/quasar-maven-plugin#2]
The groupId in the pom.xml and in your example doesn't match up with what's on mvnrepository.

http://mvnrepository.com/artifact/com.vlkan/quasar-maven-plugin/0.6.2

Is that an old version? Seems confusing if you're not going to update it.

**Comment by vy** [comment]
My bad, I had forgotten to push the local changes. Should be fixed right now.
