### ISSUE TITLE
Is there any way to scan suspendable methods automatically? 

### ISSUE THREAD

**Issue by windoze** [vy/quasar-maven-plugin#4]
The ant task shipping with quasar-core has an parameter "auto" to scan suspendable methods automatically, is there any similar settings in this plugin?
I've made a very simple project and found only methods marked with Suspendable annotation or throws SuspendExecution are actually instrumented.

**Comment by vy** [comment]
Per [Quasar Documentation](http://docs.paralleluniverse.co/quasar/#advanced-fibers) states, automatic detection of suspendable methods is still an experimental feature. Hence, I did not see a need to address it in the Maven plugin. That being said, patches are more than welcome.
