### ISSUE TITLE
quasar-maven-plugin doesn't work

### ISSUE THREAD

**Issue by githubhhb** [vy/quasar-maven-plugin#6]
add the quasar-maven-plugin in pom.xml, but it dosn't work.
Still need to add the javaagent to finish instrument.Otherwise will get an error:
Oops. Forgot to instrument a method. Run your program with -Dco.paralleluniverse.fibers.verifyInstrumentation=true to catch the culprit!
co.paralleluniverse.fibers.SuspendExecution: Oops. Forgot to instrument a method. Run your program with -Dco.paralleluniverse.fibers.verifyInstrumentation=true to catch the culprit!

**Comment by vy** [comment]
Thanks for the heads up @githubhhb. Due to lack of time, I cannot maintain this project anymore. (Let me know if you want to step up.) Further I doubt Quasar itself is maintained at all. I will put a warning about this situation to the `README`. Sorry for the trouble.
